pipeline:
  label: english
  estimator: Pipeline
  estimator_pkg: sklearn.pipeline
  estimator_params:
    steps:
      - clean html
      - detwittify
      - clean regex
      - count 3grams tfidf
      - svm

svm:
  label: svm
  estimator: LinearSVC
  estimator_pkg: sklearn.svm

tfidf:
  label: count 3grams tfidf
  estimator: TfidfVectorizer
  estimator_pkg: sklearn.feature_extraction.text
  estimator_params:
    analyzer: char
    ngram_range: [3, 3]

html cleaner:
  label: clean html
  estimator: clean_html
  estimator_pkg: pan.preprocess

detwittifier:
  label: detwittify
  estimator: detwittify
  estimator_pkg: pan.preprocess

regex cleaner:
  label: clean regex
  estimator: clean_regex
  estimator_pkg: pan.preprocess

printer:
  label: printer
  estimator: PrintWrapper
  estimator_pkg: tictacs.wrappers
